# Basic Analysis of the data

In [43]:
#Importing library
import numpy as np
import pandas as pd

In [44]:
#Loading the data
dataset = pd.read_csv('C:\\Users\\bhavi\\OneDrive\\Desktop\\Data\\Iris.csv')

In [45]:
#Checking the data
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Splitting data into X & y

In [46]:
#Splitting data into X & Y
X = dataset.iloc[:, 0:5].values #Selecting all the rows and 0 to 4 columns
y = dataset.iloc[:, 5].values #Selecting all the rows and 4th column

In [47]:
#Checking the data
print(X[0:5])
print(y[0:5])

[[1.  5.1 3.5 1.4 0.2]
 [2.  4.9 3.  1.4 0.2]
 [3.  4.7 3.2 1.3 0.2]
 [4.  4.6 3.1 1.5 0.2]
 [5.  5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


# Splitting data into Train and Test

In [48]:
#Importing library for train, test & split
from sklearn.model_selection import train_test_split

#Splitting data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Feature Scaler of the data

In [51]:
#Importing library for feature scaling
from sklearn.preprocessing import StandardScaler

#Implementing feature scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#View the data
X_train

array([[ 1.34636602,  0.61303014,  0.10850105,  0.94751783,  0.73603967],
       [ 0.16184701, -0.56776627, -0.12400121,  0.38491447,  0.34808318],
       [-1.11206965, -0.80392556,  1.03851009, -1.30289562, -1.3330616 ],
       [ 1.12287187,  0.25879121, -0.12400121,  0.60995581,  0.73603967],
       [ 1.23461894,  0.61303014, -0.58900572,  1.00377816,  1.25331499],
       [-0.39688836, -0.80392556, -0.82150798,  0.04735245,  0.21876435],
       [-1.31321439, -0.21352735,  1.73601687, -1.19037495, -1.20374277],
       [ 0.1394976 ,  0.14071157, -0.82150798,  0.72247648,  0.47740201],
       [-0.35218953,  0.02263193, -0.12400121,  0.21613346,  0.34808318],
       [ 0.34064234, -0.09544771, -1.05401024,  0.10361279, -0.03987331],
       [ 0.78763064,  1.0853487 , -0.12400121,  0.94751783,  1.12399616],
       [-1.67080503, -1.39432376,  0.34100331, -1.41541629, -1.3330616 ],
       [ 1.43576368,  1.20342834,  0.10850105,  0.72247648,  1.38263382],
       [-0.75447901, -1.04008484,  1.0

# Linear Discriminant Analysis

In [39]:
#Importing library for linear disciminat analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

#Implementing LDA
lda = LDA(n_components=1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

# Random Forest Classifier

In [40]:
#Imorting library for random forest
from sklearn.ensemble import RandomForestClassifier

#Implementing Random Forest
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Confusion Matrix and Accuracy

In [42]:
#Importing libraries for confusion matrix and accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#Creating confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#Getting accuracy
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy1.0
