In [3]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import LeavePOut
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import StratifiedKFold

In [4]:
#Creating data
X,y = make_blobs(n_samples = 10, random_state = 1)
print(X)
print(y)

[[ -7.23731039  -9.03108652]
 [ -8.16550136  -7.00850439]
 [ -7.02266844  -7.57041289]
 [ -8.86394306  -5.05323981]
 [  0.08525186   3.64528297]
 [ -0.79415228   2.10495117]
 [ -1.34052081   4.15711949]
 [-10.32012971  -4.3374029 ]
 [ -2.18773166   3.33352125]
 [ -8.53560457  -6.01348926]]
[2 2 2 1 0 0 0 1 0 1]


# Exhaustive Method of Cross Validation:

## Leave p-out cross-validation

In [5]:
#Using Leave P-Out Cross Validation
#P value should be less the number of observation
LPO_CV = LeavePOut(p=2)
for i,j in LPO_CV.split(X):
    print(i,j)
#Extracting observation from the data for validation more than 1 and less than the total number of observation

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

## Leave One Out Cross Validation

In [6]:
#Onle one observation can extract from the data for validation
LOO_CV = LeaveOneOut()
for i,j in LOO_CV.split(X):
    print(i,j)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


# Non - Exhaustive Method of Cross Validation

## Hold-Out Cross Validation

In [7]:
#Simply dividing the data into train and test with the ratio of 80-20
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)
X_train

array([[  0.08525186,   3.64528297],
       [ -1.34052081,   4.15711949],
       [-10.32012971,  -4.3374029 ],
       [ -8.16550136,  -7.00850439],
       [ -7.23731039,  -9.03108652],
       [ -8.53560457,  -6.01348926],
       [ -8.86394306,  -5.05323981],
       [ -2.18773166,   3.33352125]])

## K-Fold Cross Validation

In [8]:
#Creating k number of fold for the validation
#k should not be greater than the total number of observation
KFold_CV = KFold(n_splits=10)
for i,j in KFold_CV.split(X):
    print(i,j)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


## Repeated Cross Validation

In [9]:
#Repeating the k number of folds more than one
# We can repeating the k fold n numbers of time 
R_CV = RepeatedKFold(n_splits=5, n_repeats=2)
for i,j in R_CV.split(X):
    print(i,j)

[0 3 4 5 6 7 8 9] [1 2]
[1 2 3 4 5 6 7 8] [0 9]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 3 4 5 6 9] [7 8]
[0 1 2 3 6 7 8 9] [4 5]
[0 2 3 5 6 7 8 9] [1 4]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 3 4 5 6 7] [8 9]
[1 2 3 4 5 6 8 9] [0 7]


## Stratify Cross Validation

In [20]:
#It will equal balance the data i.e. 50% for train & 50% for testing
#It is used for data have class imbalance
S_CV = StratifiedKFold(n_splits=4)
for i,j in S_CV.split(X,y):
    print(i,j)

[1 2 5 6 7 8 9] [0 3 4]
[0 2 3 4 6 8 9] [1 5 7]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 2 3 4 5 6 7] [8 9]


c:\users\bhavi\appdata\local\programs\python\python38\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=4.
  warnings.warn(("The least populated class in y has only %d"


In [ ]:
cross_